/**
 * Enhanced Neurophoto Action
 * Integration with Avatar Faces system for personalized image generation
 *
 * Supports:
 * - /neurophoto <prompt> - Use default face
 * - /neurophoto face:<name> <prompt> - Use specific face
 * - /neurophoto raw <prompt> - Generate without LoRA
 */

import { Action, ActionResult, IAgentRuntime, Memory, State, logger } from '@elizaos/core';
import { FalMcpService } from '../services/FalMcpService';
import { FaceManagerService } from '../services/FaceManagerService';

export const enhancedNeurophotoAction: Action = {
  name: 'GENERATE_NEUROPHOTO_WITH_FACE',
  similes: [
    'MAKE_IMAGE',
    'CREATE_PHOTO',
    'NEUROPHOTO',
    'GENERATE_IMAGE',
    'AI_IMAGE',
    'DRAW_IMAGE',
    'НАРИСУЙ',
    'СОЗДАЙ_ИЗОБРАЖЕНИЕ',
  ],
  description: `Generates AI images with LoRA avatar faces.

Use when user:
- Asks to draw/create/generate an image
- Wants to see how something looks
- Uses /neurophoto command
- Wants to use a specific face with face:<name>

Features:
- Uses avatar faces (LoRA models)
- Supports face selection: face:<name>
- Default face used if no face specified
- Raw generation without LoRA: raw keyword`,

  validate: async (runtime: IAgentRuntime, message: Memory): Promise<boolean> => {
    const text = message.content?.text?.toLowerCase();
    if (!text) return false;

    // Direct command triggers
    const commands = ['/neurophoto', 'нейрофото', 'neurophoto'];
    if (commands.some((cmd) => text.includes(cmd))) {
      return true;
    }

    // Intent-based triggers (natural language)
    const intents = [
      // Russian
      'нарисуй',
      'создай изображение',
      'сгенерируй',
      'сделай картинк',
      'хочу фото',
      'покажи как выглядит',
      'сделай фото',
      // English
      'generate image',
      'create image',
      'draw',
      'make a picture',
      'show me how',
      'can you draw',
      'make an image',
    ];

    return intents.some((intent) => text.includes(intent));
  },

  handler: async (runtime: IAgentRuntime, message: Memory, state?: State, options?: any, callback?: any): Promise<ActionResult> => {
    try {
      logger.info('🎨 [NEUROPHOTO] Starting enhanced image generation...');

      const falMcp = runtime.getService<FalMcpService>('fal-mcp' as any);
      const faceManager = runtime.getService<FaceManagerService>('face-manager' as any);

      const userId = message.userId;
      const text = message.content?.text;

      if (!text) {
        await callback({
          text: 'No text in message',
        });
        return {
          success: false,
          error: new Error('No text in message'),
        };
      }

      // Parse prompt and face selection
      const parsed = parseNeurophotoCommand(text);

      if (!parsed.prompt || parsed.prompt.length < 3) {
        const helpText = getNeurophotoHelpText();
        await callback({
          text: helpText,
        });
        return {
          success: false,
          error: new Error('Prompt too short'),
        };
      }

      logger.info(`📝 [NEUROPHOTO] Prompt: ${parsed.prompt}`);
      logger.info(`🎭 [NEUROPHOTO] Face: ${parsed.faceName || 'default'}`);
      logger.info(`🔧 [NEUROPHOTO] Raw mode: ${parsed.rawMode}`);

      // Send "generating" message
      if (parsed.rawMode) {
        await callback({
          text: '🎨 Generating image without personalization (raw mode), this will take 20-40 seconds...',
        });
      } else {
        await callback({
          text: `🎨 Generating image with your ${parsed.faceName ? `"${parsed.faceName}"` : 'default'} face, this will take 20-40 seconds...`,
        });
      }

      const startTime = Date.now();
      let result;

      if (parsed.rawMode) {
        // Generate without LoRA
        result = await falMcp.generateRaw(parsed.prompt);

        if (!result.success || !result.data) {
          throw new Error(result.error?.message || 'Failed to generate image');
        }

        const generationTime = Date.now() - startTime;

        const resultText = formatRawResult(parsed.prompt, result.data, generationTime);

        await callback({
          text: resultText,
          attachments: [
            {
              id: `neurophoto-raw-${Date.now()}`,
              url: result.data,
              contentType: 'image/jpeg',
              title: parsed.prompt,
              description: 'Generated by Flux (raw, no LoRA)',
            },
          ],
        });

        return {
          success: true,
          text: 'Image generated successfully (raw)',
          data: {
            imageUrl: result.data,
            prompt: parsed.prompt,
            mode: 'raw',
            generationTime,
          },
        };
      } else {
        // Generate with face
        result = await falMcp.generateWithFace({
          userId,
          faceName: parsed.faceName,
          prompt: parsed.prompt,
          imageSize: parsed.imageSize,
        });

        if (!result.success || !result.data) {
          // Handle "no default face" error specially
          if (result.error?.code === 'NO_DEFAULT_FACE') {
            await callback({
              text: `You don't have a default face set yet!\n\nTo use this feature:\n1. Add a face: \`/face add <name> <lora_url> <trigger>\`\n2. Or train a new face: \`/face train <name> <images_zip_url> <trigger>\`\n3. Set it as default: \`/face use <name>\`\n\nOr generate without personalization: \`/neurophoto raw <prompt>\``,
            });
          } else {
            throw new Error(result.error?.message || 'Failed to generate image');
          }

          return {
            success: false,
            error: new Error(result.error?.message || 'Failed to generate image'),
          };
        }

        const generation = result.data;
        const resultText = formatFaceResult(parsed.prompt, generation);

        await callback({
          text: resultText,
          attachments: [
            {
              id: `neurophoto-${generation.generationId}`,
              url: generation.imageUrl,
              contentType: 'image/jpeg',
              title: parsed.prompt,
              description: `Generated with ${generation.faceName} (${generation.triggerWord})`,
            },
          ],
        });

        return {
          success: true,
          text: 'Image generated successfully',
          data: {
            imageUrl: generation.imageUrl,
            prompt: parsed.prompt,
            faceName: generation.faceName,
            triggerWord: generation.triggerWord,
            generationTime: generation.generationTimeMs,
            generationId: generation.generationId,
          },
        };
      }
    } catch (error) {
      logger.error({ error }, '❌ [NEUROPHOTO] Generation failed:');

      await callback({
        text: `Failed to generate image: ${error instanceof Error ? error.message : String(error)}`,
      });

      return {
        success: false,
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  },

  examples: [
    [
      {
        name: 'user',
        content: { text: '/neurophoto sunset over the ocean' },
      },
      {
        name: 'Vibee',
        content: {
          text: '✨ Image created with your default face!',
          actions: ['GENERATE_NEUROPHOTO_WITH_FACE'],
        },
      },
    ],
    [
      {
        name: 'user',
        content: { text: '/neurophoto face:Professional in a business suit' },
      },
      {
        name: 'Vibee',
        content: {
          text: '✨ Image created with "Professional" face!',
          actions: ['GENERATE_NEUROPHOTO_WITH_FACE'],
        },
      },
    ],
    [
      {
        name: 'user',
        content: { text: '/neurophoto raw a beautiful landscape' },
      },
      {
        name: 'Vibee',
        content: {
          text: '✨ Image created (raw, no personalization)',
          actions: ['GENERATE_NEUROPHOTO_WITH_FACE'],
        },
      },
    ],
  ],
};

// ============================================================================
// Utilities
// ============================================================================

interface ParsedNeurophotoCommand {
  prompt: string;
  faceName?: string;
  rawMode: boolean;
  imageSize?: 'portrait_4_3' | 'portrait_16_9' | 'landscape_4_3' | 'landscape_16_9' | 'square_hd';
}

function parseNeurophotoCommand(text: string): ParsedNeurophotoCommand {
  // Remove command prefixes
  let cleaned = text
    .replace(/\/neurophoto/gi, '')
    .replace(/нейрофото/gi, '')
    .replace(/создай изображение/gi, '')
    .replace(/нарисуй/gi, '')
    .replace(/generate image/gi, '')
    .trim();

  // Check for raw mode
  const rawMode = /^raw\s+/i.test(cleaned);
  if (rawMode) {
    cleaned = cleaned.replace(/^raw\s+/i, '').trim();
  }

  // Extract face name (format: face:<name> or face:"name with spaces")
  let faceName: string | undefined;
  const faceMatch = cleaned.match(/face:(?:"([^"]+)"|([^\s]+))/i);
  if (faceMatch) {
    faceName = faceMatch[1] || faceMatch[2];
    cleaned = cleaned.replace(/face:(?:"[^"]+"|[^\s]+)\s*/gi, '').trim();
  }

  // Extract size (optional)
  let imageSize: any = 'portrait_4_3'; // Default
  const sizeMatch = cleaned.match(/size:(portrait_4_3|portrait_16_9|landscape_4_3|landscape_16_9|square_hd)/i);
  if (sizeMatch) {
    imageSize = sizeMatch[1];
    cleaned = cleaned.replace(/size:[^\s]+\s*/gi, '').trim();
  }

  return {
    prompt: cleaned,
    faceName,
    rawMode,
    imageSize,
  };
}

function formatFaceResult(prompt: string, generation: any): string {
  return `✨ **Image created!**

━━━━━━━━━━━━━━━━━━━━
📝 **Prompt**
${prompt.slice(0, 150)}${prompt.length > 150 ? '...' : ''}

🎭 **Face Details**
├ 👤 Face: **${generation.faceName}**
├ 🎯 Trigger: \`${generation.triggerWord}\`
├ 🤖 Model: **Flux LoRA**
└ ⏱ Time: **${Math.round(generation.generationTimeMs / 1000)}s**

━━━━━━━━━━━━━━━━━━━━
🔧 **Commands**
Use different face: \`/neurophoto face:<name> <prompt>\`
List faces: \`/faces\`
Raw mode: \`/neurophoto raw <prompt>\`

_Created with AI • Vibee_`;
}

function formatRawResult(prompt: string, imageUrl: string, generationTime: number): string {
  return `✨ **Image created (raw mode)!**

━━━━━━━━━━━━━━━━━━━━
📝 **Prompt**
${prompt.slice(0, 150)}${prompt.length > 150 ? '...' : ''}

🤖 **Generation Details**
├ 🎭 Mode: **Raw (no LoRA)**
├ 🤖 Model: **Flux**
└ ⏱ Time: **${Math.round(generationTime / 1000)}s**

━━━━━━━━━━━━━━━━━━━━
💡 **Want personalization?**
Add a face: \`/face add <name> <lora_url> <trigger>\`
Train a face: \`/face train <name> <images_zip> <trigger>\`

_Created with AI • Vibee_`;
}

function getNeurophotoHelpText(): string {
  return `**Neurophoto - AI Image Generation**

**Basic Usage:**
\`/neurophoto <prompt>\` - Use your default face

**Advanced Usage:**
\`/neurophoto face:<name> <prompt>\` - Use specific face
\`/neurophoto raw <prompt>\` - Generate without LoRA
\`/neurophoto size:portrait_16_9 <prompt>\` - Set size

**Size Options:**
- \`portrait_4_3\` (default)
- \`portrait_16_9\`
- \`landscape_4_3\`
- \`landscape_16_9\`
- \`square_hd\`

**Examples:**
\`/neurophoto sunset over the ocean\`
\`/neurophoto face:Professional in a business suit\`
\`/neurophoto raw a beautiful mountain landscape\`
\`/neurophoto face:Casual size:square_hd at a coffee shop\`

**Face Management:**
\`/faces\` - List your faces
\`/face use <name>\` - Set default face
\`/face add <name> <lora_url> <trigger>\` - Add face

Please provide a description for the image you want to create.`;
}
